# Generated by Django 6.0.3 on 2026-03-21 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_comment_attachment_ticket_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
